// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyCyuZ3k8gV0R1Vgvq8kLZkLtshVfTGtspE",
authDomain: "gold2-db778.firebaseapp.com",
projectId: "gold2-db778",
storageBucket: "gold2-db778.appspot.com",
messagingSenderId: "607647310929",
appId: "1:607647310929:web:e7f6f0275cf4ab1f320470",

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyCyuZ3k8gV0R1Vgvq8kLZkLtshVfTGtspE",
  authDomain: "gold2-db778.firebaseapp.com",
  projectId: "gold2-db778",
  storageBucket: "gold2-db778.appspot.com",
  messagingSenderId: "607647310929",
  appId: "1:607647310929:web:e7f6f0275cf4ab1f320470"
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyB3tElCaYh3GbEIZTPnIWGW-6_1AYLMVyhrs",
  appId: "1:607647310929:web:e7f6f0275cf4ab1f320470",
  messagingSenderId: "607647310929",
  projectId: "gold2-db778",
  storageBucket: "gold2-db778.appspot.com",
  iosClientId: "ios-client-id.apps.googleusercontent.com", 
  iosBundleId: "com.example.goldPrice1",
    
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyB3tElCaYh3GbEIZTPnIWGW-6_1AYLMVyhrs",
  appId: "1:607647310929:web:e7f6f0275cf4ab1f320470",
  messagingSenderId: "607647310929",
  projectId: "gold2-db778",
  storageBucket: "gold2-db778.appspot.com",
  iosClientId: "ios-client-id.apps.googleusercontent.com", // أو اتركها مؤقتًا
  iosBundleId: "com.example.goldPrice1",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyCyuZ3k8gV0R1Vgvq8kLZkLtshVfTGtspE",
  appId: "1:607647310929:web:e7f6f0275cf4ab1f320470",
  messagingSenderId: "607647310929",
  projectId: "gold2-db778",
  authDomain: "gold2-db778.firebaseapp.com",
  storageBucket: "gold2-db778.appspot.com",
  );
}